version: '2'

networks:
  consul-network:
    driver: bridge

services:
  consul:
    image: 'bitnami/consul:latest'
    networks:
      - consul-network
    environment:
      - CONSUL_HTTP_PORT_NUMBER=8888
    ports:
      - '8888:8888'
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
  
  fp-auth:
    image: 'fp-auth'
    build:
      context: .
      dockerfile: FP-Auth/Dockerfile
    networks:
      - consul-network
    environment:
      - CONSUL_CONF_BASE_URL=http://consul:8888
      - CONSUL_CONF_ID=FP-Auth
      - CONSUL_CONF_NAME=FP-Auth
      - CONSUL_CONF_ADDRESS=fp-auth
      - CONSUL_CONF_PORT=80
    restart: always

  fp-fap:
    image: 'fp-fap'
    build:
      context: .
      dockerfile: FP-FAP/Dockerfile
    networks:
      - consul-network
    environment:
      - CONSUL_CONF_BASE_URL=http://consul:8888
      - CONSUL_CONF_ID=FP-FAP
      - CONSUL_CONF_NAME=FP-FAP
      - CONSUL_CONF_ADDRESS=fp-fap
      - CONSUL_CONF_PORT=80
    restart: always
  
  fp-chat:
    image: 'fp-chat'
    build:
      context: .
      dockerfile: FP-Chat/Dockerfile
    networks:
      - consul-network
    environment:
      - CONSUL_CONF_BASE_URL=http://consul:8888
      - CONSUL_CONF_ID=FP-Chat
      - CONSUL_CONF_NAME=FP-Chat
      - CONSUL_CONF_ADDRESS=fp-chat
      - CONSUL_CONF_PORT=80
    restart: always
  
  nginx:
    build:
      context: FP-Nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - consul-network
    restart: always
    depends_on:
      - fp-auth
      - fp-chat
      - fp-fap