name: FP-Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_run:
    runs-on: self-hosted
    defaults:
      run:
          working-directory: PRN231-FP  
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/variable-substitution@v1
      with:
        files: 'PRN231-FP/FP-FAP/appsettings.secret.json'
      env:
        ConnectionStrings.DB: ${ secret.CONNECTION_STRING }
        Jwt.Key: ${ secret.JWT_KEY }
    - name: Prune Unused Resource
      run: docker system prune -af
    - name: Compose Up
      run: docker-compose up -d --build --remove-orphans
